version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
      groups:
          docusaurus:
              patterns:
                  - "@docusaurus/*" # Make sure all docusaurus packages are updated together
      open-pull-requests-limit: 10
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: daily
      open-pull-requests-limit: 10
