version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: monthly
      groups:
          docusaurus:
              patterns:
                  - "@docusaurus/*" # Make sure all docusaurus packages are updated together
          docusaurus-api:
              patterns:
                  - "*-openapi-docs" # Make sure all api docs plugins are updated together
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: monthly
